// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import ()

type User struct {
	Id          int32
	Name        string
	Description string
	Age         int32
	SomeID      int32
}
